export { Dashboard } from './dashboard'
export { Payment } from './payment'
export { Commands } from './commands'
export { Faq } from './faq'
export { Landing } from './landing'
export { Music } from './music'
export { Support } from './support'